merge_queue:
  max_parallel_checks: 2

queue_rules:
  - name: default
    batch_size: 1
    queue_conditions:
      - -scope = critical
    merge_conditions:
      - check-success = ci-gate

scopes:
  source:
    files:
      critical:
        include:
          - critical/**
  merge_queue_scope: merge-queue
